[versions]
io-prometheus-simpleclient-common = "0.16.0"
jupiterVersion = "6.0.1"
kotlinVersion = "2.3.0"
mockkVersion = "1.14.7"
net-logstash-logback-logstash-logback-encoder = "9.0"
org-skyscreamer-jsonassert = "1.5.3"
org-springdoc-springdoc-openapi-starter-webmvc-ui = "3.0.0"
springBootVersion = "4.0.1"
springDependencyManagementVersion = "1.1.7"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBootVersion" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }

[libraries]
io-prometheus-simpleclient-common = { module = "io.prometheus:simpleclient_common", version.ref = "io-prometheus-simpleclient-common" }
net-logstash-logback-logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "net-logstash-logback-logstash-logback-encoder" }
org-skyscreamer-jsonassert = { module = "org.skyscreamer:jsonassert", version.ref = "org-skyscreamer-jsonassert" }
org-springdoc-springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "org-springdoc-springdoc-openapi-starter-webmvc-ui" }
org-springframework-boot-spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc", version.ref = "springBootVersion" }
org-springframework-boot-spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test", version.ref = "springBootVersion" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiterVersion" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "jupiterVersion" }
mockk = { module = "io.mockk:mockk", version.ref = "mockkVersion" }